In [1]:
import pandas as pd

# Load dataset (update file path if needed)
df = pd.read_csv("C:\\Users\\HP\\OneDrive\\Desktop\\cleant1\\amazon_products.csv")

# Display first few rows
df.head()

,Product Name,Price,Rating,Reviews,Discount,Availability,Delivery Date
0,Lenovo IdeaPad Slim 5 12th Gen Intel Core i5 1...,"₹60,190",3.9,771,(20% off),In stock,"FREE delivery Saturday, 1 March. Details"
1,Lenovo IdeaPad Slim 3 12th Gen Intel Core i5-1...,"₹54,090",3.9,462,(23% off),In stock,"FREE delivery Saturday, 1 March. Details\nOr f..."
2,Acer Aspire Lite AMD Ryzen 5-5625U Premium Thi...,"₹34,490",3.9,"1,052",(42% off),In stock,"FREE delivery Saturday, 1 March. Details\nOr f..."
3,(Refurbished) Lenovo ThinkPad 8th Gen Intel Co...,"₹17,498",3.3,236,(65% off),In stock,"FREE delivery Sunday, 2 March. Details\nOr fas..."
4,"HP 15, 12th Gen Intel Core i5-1235U, 16GB DDR4...","₹49,990",3.9,327,(20% off),In stock,"FREE delivery Saturday, 1 March. Details\nOr f..."

In [5]:
import pandas as pd

# Load the dataset
file_path = "C:\\Users\\HP\\OneDrive\\Desktop\\cleant1\\amazon_products.csv"  # Update if needed
df = pd.read_csv(file_path)

# Function to clean numeric columns safely
def clean_numeric(column):
    # Convert to string only if not already numeric
    if column.dtype == "object":
        return pd.to_numeric(column.str.replace(r"[₹,]", "", regex=True), errors="coerce")
    return column  # If already numeric, return as is

# Apply only if the column exists
if "Price" in df.columns:
    df["Price"] = clean_numeric(df["Price"])

if "Reviews" in df.columns:
    df["Reviews"] = clean_numeric(df["Reviews"])

# Print data types to verify
print(df.dtypes)

Product Name      object
Price            float64
Rating           float64
Reviews          float64
Discount          object
Availability      object
Delivery Date     object
dtype: object

In [6]:
if "Discount" in df.columns:
    df["Discount"] = df["Discount"].str.extract(r"(\d+)").astype(float)

# Print the first few rows to check the output
print(df[["Discount"]].head())

   Discount
0      20.0
1      23.0
2      42.0
3      65.0
4      20.0

In [7]:
import pandas as pd
import re

# Remove text after "Details"
if "Delivery Date" in df.columns:
    df["Delivery Date"] = df["Delivery Date"].str.split("Details").str[0].str.strip()

# Function to extract only the date
def extract_date(text):
    if pd.isna(text) or text.strip() == "":
        return "Unknown"
    
    match = re.search(r"\b(?:\d{1,2} [A-Za-z]+|\d{1,2} [A-Za-z]+ - \d{1,2} [A-Za-z]+)\b", str(text))
    return match.group(0) if match else "Unknown"

# Apply function
if "Delivery Date" in df.columns:
    df["Delivery Date"] = df["Delivery Date"].apply(extract_date)

# Print the cleaned "Delivery Date" column
print(df[["Delivery Date"]].head())

  Delivery Date
0       1 March
1       1 March
2       1 March
3       2 March
4       1 March

In [8]:
import pandas as pd

# Fill missing values
if "Rating" in df.columns:
    df["Rating"] = df["Rating"].fillna(df["Rating"].median())

if "Reviews" in df.columns:
    df["Reviews"] = df["Reviews"].fillna(0)

if "Discount" in df.columns:
    df["Discount"] = df["Discount"].fillna(0)

if "Availability" in df.columns:
    df["Availability"] = df["Availability"].fillna("Unknown")

# Print the updated columns
print("Updated Rating Column:")
print(df[["Rating"]].head())  # Print first few values

print("\nUpdated Reviews Column:")
print(df[["Reviews"]].head())

print("\nUpdated Discount Column:")
print(df[["Discount"]].head())

print("\nUpdated Availability Column:")
print(df[["Availability"]].head())

Updated Rating Column:
   Rating
0     3.9
1     3.9
2     3.9
3     3.3
4     3.9

Updated Reviews Column:
   Reviews
0    771.0
1    462.0
2   1052.0
3    236.0
4    327.0

Updated Discount Column:
   Discount
0      20.0
1      23.0
2      42.0
3      65.0
4      20.0

Updated Availability Column:
  Availability
0     In stock
1     In stock
2     In stock
3     In stock
4     In stock

In [10]:
if "Availability" in df.columns:
    df["Availability"] = df["Availability"].str.replace("\n", " ", regex=True)

    df["Availability"] = df["Availability"].replace({
        "Unavailable We don't know when or if this item will be back in stock.": "Unavailable"
    })

    # Print the updated "Availability" column
    print("\nUpdated Availability Column:")
    print(df[["Availability"]].head())  # Display first few rows

Updated Availability Column:
  Availability
0     In stock
1     In stock
2     In stock
3     In stock
4     In stock

In [11]:
if "Availability" in df.columns:
    df["Availability"] = df["Availability"].str.strip().replace({
        "Only 1 left in stock.": "1 Left",
        "Only 2 left in stock.": "2 Left",
        "Currently unavailable.": "Unavailable",
        "We don’t know when or if this item will be back in stock.": "Unavailable",
        "In stock.": "In Stock",
        "Unknown": "Unavailable",
        "Unavailable": "Unavailable"  
    }, regex=True)

    # Print the updated "Availability" column
    print("\nUpdated Availability Column:")
    print(df[["Availability"]].head())  # Display first few rows

Updated Availability Column:
  Availability
0     In stock
1     In stock
2     In stock
3     In stock
4     In stock

In [18]:
import os

# Define the folder path
folder_path = "C:\\Users\\HP\\OneDrive\\Desktop\\cleant1"

# Create the folder if it doesn't exist
if not os.path.exists(folder_path):
    os.makedirs(folder_path)

# Define file path
file_path = os.path.join(folder_path, "cleandata.xlsx")

# Save the cleaned data
df.to_excel(file_path, index=False)

print(f"✅ Data cleaning completed! Check the file at: {file_path}")

✅ Data cleaning completed! Check the file at: C:\Users\HP\OneDrive\Desktop\cleant1\cleandata.xlsx

In [19]:

df.head()

,Product Name,Price,Rating,Reviews,Discount,Availability,Delivery Date
0,Lenovo IdeaPad Slim 5 12th Gen Intel Core i5 1...,60190.0,3.9,771.0,20.0,In stock,1 March
1,Lenovo IdeaPad Slim 3 12th Gen Intel Core i5-1...,54090.0,3.9,462.0,23.0,In stock,1 March
2,Acer Aspire Lite AMD Ryzen 5-5625U Premium Thi...,34490.0,3.9,1052.0,42.0,In stock,1 March
3,(Refurbished) Lenovo ThinkPad 8th Gen Intel Co...,17498.0,3.3,236.0,65.0,In stock,2 March
4,"HP 15, 12th Gen Intel Core i5-1235U, 16GB DDR4...",49990.0,3.9,327.0,20.0,In stock,1 March

In [8]:
import pandas as pd

# Load the dataset
file_path = "C:\\Users\\HP\\OneDrive\\Desktop\\cleant1\\clean45\\cleandata.xlsx"  # Replace with your actual file path
df = pd.read_excel(file_path)

# Handling missing values
df['Price'] = df['Price'].fillna(df['Price'].median())  # Replace missing values with median price

# Save the cleaned dataset
cleaned_file_path = "C:\\Users\\HP\\OneDrive\\Desktop\\cleant1\\clean45.xlsx"  # Ensure the .xlsx extension
df.to_excel(cleaned_file_path, index=False)

print("✅ Dataset cleaned successfully and saved as 'clean45.xlsx'")

✅ Dataset cleaned successfully and saved as 'clean45.xlsx'

In [9]:
import pandas as pd

# Load the dataset
file_path = "C:\\Users\\HP\\OneDrive\\Desktop\\cleant1\\clean45\\cleandata.xlsx"  # Update with your actual file path
df = pd.read_excel(file_path)

# Handling missing values in the "Price" column
df['Price'] = df['Price'].fillna(df['Price'].median())

# Removing duplicate rows
df = df.drop_duplicates()

# Save the cleaned dataset
cleaned_file_path = "C:\\Users\\HP\\OneDrive\\Desktop\\cleant1\\clean45\\cleannew.xlsx"  # Ensure .xlsx extension
df.to_excel(cleaned_file_path, index=False)

print("✅ Dataset cleaned successfully: Missing values handled and duplicate rows removed.")

✅ Dataset cleaned successfully: Missing values handled and duplicate rows removed.

In [10]:
df.head()

,Product Name,Price,Rating,Reviews,Discount,Availability,Delivery Date
0,Lenovo IdeaPad Slim 5 12th Gen Intel Core i5 1...,60190.0,3.9,771,20,In stock,1 March
1,Lenovo IdeaPad Slim 3 12th Gen Intel Core i5-1...,54090.0,3.9,462,23,In stock,1 March
2,Acer Aspire Lite AMD Ryzen 5-5625U Premium Thi...,34490.0,3.9,1052,42,In stock,1 March
3,(Refurbished) Lenovo ThinkPad 8th Gen Intel Co...,17498.0,3.3,236,65,In stock,2 March
4,"HP 15, 12th Gen Intel Core i5-1235U, 16GB DDR4...",49990.0,3.9,327,20,In stock,1 March